BeMyNeighbor.MVCClient/Models/ErrorViewModel.cs
using System;

namespace BeMyNeighbor.MVCClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BeMyNeighbor.MVCClient/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using BeMyNeighbor.Domain.Models;
using BeMyNeighbor.Domain.Models.DbModels;
using BeMyNeighbor.Data.Entities;

namespace BeMyNeighbor.MVCClient.Controllers{
  public class AuthController: Controller{
    [HttpGet]
    public ViewResult SignIn(){
      //clean good or bad messaages
      if(CurrentUser.Storage().Messages.DestinationType != "/Auth/SignIn"){
        CurrentUser.Storage().CleanMessages();
      }
      return View(CurrentUser.Storage());
    }

    [HttpGet]
    public ViewResult SignUp(){
      if(CurrentUser.Storage().Messages.DestinationType != "/Auth/SignUp"){
        CurrentUser.Storage().CleanMessages();
      }
      return View(CurrentUser.Storage());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public RedirectToActionResult SignUp(LocalUser newUser){
      if(UserDbManager.GetInstance().SignUp(newUser)){
        //sign up successfuly 
        return RedirectToAction("SignIn", "Auth");
      }
      //sign up failed
      return RedirectToAction("SignUp","Auth");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public RedirectToActionResult SignIn(LocalUser user){
      if(!UserDbManager.GetInstance().SignIn(user)){
          return RedirectToAction("SignIn", "Auth");
      }
      var curr = CurrentUser.Storage();
      return RedirectToAction("Index", "Main");
    }

    public RedirectToActionResult Logout(){
      CurrentUser.DeleteStorage();
      return RedirectToAction("Index", "Home");
    }
  }
}

BeMyNeighbor.MVCClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BeMyNeighbor.MVCClient.Models;
using BeMyNeighbor.Domain.Models;

namespace BeMyNeighbor.MVCClient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BeMyNeighbor.MVCClient/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using BeMyNeighbor.Domain.Models;
using BeMyNeighbor.Domain.Models.DbModels;

namespace BeMyNeighbor.MVCClient.Controllers{
  public class MainController: Controller{
    public IActionResult Index(){

      /*
        We are routing as such to preserve the unqiue URI
      */
      //Here is here we want to load community and post infomration 
      if(CurrentUser.Storage().UserDb.Username == null){
        return RedirectToAction("Index", "Home");
      }
      if(!CurrentUser.Storage().UserDb.VerifiedUser){
        return RedirectToAction("SelectCommunity", "Main");
        // return View("../Main/_SelectCommunity", CurrentUser.Storage());
      }
      if(CurrentUser.Storage().Messages.DestinationType != "/Main/Index"){
        CurrentUser.Storage().CleanMessages();
      }
      CurrentUser.Storage().Messages.ReduceDuration();
      //reget the post for user 
      //if the user has been verified go to index
      return View(CurrentUser.Storage());
    }

    [HttpGet]
    public ViewResult SelectCommunity(){
      UserDbManager.GetInstance().CommunityListByUserLocation();
      return View(CurrentUser.Storage());
    }

    [HttpPost]
    public RedirectToActionResult SelectedCommunity(LocalUser info){
      //here is where we are going to verify the user 
      UserDbManager.GetInstance().UserSelectedCommunity(info.SelectedCommunity);
      var userCur = CurrentUser.Storage().UserDb;
      // return View("../Main/Index", CurrentUser.Storage());
      return RedirectToAction("Index", "Main");
    }

    [HttpPost]
    public RedirectToActionResult SelectedJob(int selectedPostId){
      PostDbManager.SelectedOtherUsersPost(selectedPostId);
      return RedirectToAction("Index", "Main");
    }

    public ViewResult ViewJobList(){
      return View("JobsList",PostDbManager.FetchPostsLinkedWithUserID(CurrentUser.Storage().UserDb.UserId));
    }

  }
}

BeMyNeighbor.MVCClient/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using BeMyNeighbor.Domain.Models;
using BeMyNeighbor.Domain.Models.DbModels;
using BeMyNeighbor.Domain.Models.ViewModels;

namespace BeMyNeighbor.MVCClient.Controllers{
  public class PostController: Controller{
    public RedirectToActionResult Index(){
      return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public ViewResult Create(){
    
      return View(new CreatePostViewModel());
    }

    [HttpPost]
    public IActionResult Create(CreatePostViewModel model){
      PostDbManager.CreatePost(model);
      return RedirectToAction("Index", "Main");
    }

    public IActionResult CommunityPosts(){
      ViewBag.listOfPosts = PostDbManager.FetchPostsByCommunityId(CurrentUser.Storage().UserDb.CommunityId);
      
      return View();
    }

    public IActionResult SelectedPost(int postId){
      PostDbManager.SelectedPost(postId);
      return View();
    }

  }
}

BeMyNeighbor.MVCClient/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using BeMyNeighbor.Domain.Models.DbModels;
using BeMyNeighbor.Domain.Models;
using System.Collections.Generic;
using BeMyNeighbor.Data.Entities;
using System;

namespace BeMyNeighbor.MVCClient.Controllers{
  public class UserController : Controller{
    public IActionResult SignupPage(){
      return View("UserSignupPage",CommunityDbManager.GetInstance().PullAllCommunities());
    }
  }
}

BeMyNeighbor.MVCClient/Controllers/UserEvaluationController.cs
using Microsoft.AspNetCore.Mvc;
using BeMyNeighbor.Domain.Models.DbModels;
using BeMyNeighbor.Domain.Models;
using System.Collections.Generic;
using BeMyNeighbor.Domain.Models.ViewModels;
using System;

namespace BeMyNeighbor.MVCClient.Controllers
{
    public class UserEvaluationController : Controller{
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StartNewEvaluation(int postID,int selectedUserID,int taskTypeID){

            CurrentUser.Storage().CreatePostViewModel.userId = selectedUserID;
            CurrentUser.Storage().CreatePostViewModel.evaluationPostID = postID;
            CurrentUser.Storage().CreatePostViewModel.TaskTypeId = taskTypeID;
            return View ("EvaluateUser",QuestionsDbManager.GetInstance().QuestionsList);
        }
        public IActionResult ViewEvaluationHistory(){
            
            return View("ViewEvaluationHistory", 
            EvaluationDbManager.GetInstance().ListUserEvaluation(CurrentUser.Storage().UserDb.UserId));
        }

[HttpPost]
[ValidateAntiForgeryToken]
        public IActionResult SubmitEvaluation (List<string> QuestionScore){
            EvaluationDbManager.GetInstance().PushEvaluation(QuestionScore,
            CurrentUser.Storage().CreatePostViewModel.evaluationPostID,
            CurrentUser.Storage().CreatePostViewModel.userId, 
            CurrentUser.Storage().CreatePostViewModel.TaskTypeId);
            return RedirectToAction("Index", "Main");
        }
        
    }
}

BeMyNeighbor.MVCClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "../Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BeMyNeighbor.MVCClient/Views/Main/Index.cshtml
@model BeMyNeighbor.Domain.Models.LocalUser;

@{
  Layout = "../Shared/_UserMainLayout.cshtml";
}

<div>
  @if(@Model.Messages.MessageType == "UnableToAcceptPost"){
    <div class="row justify-content-md-center">
          <div class="row alert alert-danger justify-content-center col-md-5">@Model.Messages.MessageToUser</div>
    </div>
  }
  @if(@Model.Messages.MessageType == "SuccessfulyEvaluation"){
    <div class="row justify-content-md-center">
        <div class="row alert alert-success justify-content-center col-md-5">@Model.Messages.MessageToUser</div>
    </div>
  }
  @if(@Model.Messages.MessageType == "FailedEvaluation"){
    <div class="row justify-content-md-center">
        <div class="row alert alert-danger justify-content-center col-md-5">@Model.Messages.MessageToUser</div>
    </div>
  }
  <div class="UserMainContent col-lg-12">
    <div class="UserProfile">
        @Html.Partial("../Shared/_UserProfile.cshtml", @Model.UserDb)
    </div>

    <div class="PostFeed">
      @Html.Partial("../Shared/Post/_PostForm.cshtml", @Model.CreatePostViewModel)
      @foreach(var tupleObject in BeMyNeighbor.Domain.Models.DbModels.PostDbManager.FetchPostsByUsersCommunityId()){
        @Html.Partial("../Shared/Post/_PostItem.cshtml", @tupleObject);
      }      
    </div>

    <div class="Map">
      <p>Map</p>
    </div>
  </div>
</div>

BeMyNeighbor.MVCClient/Views/Main/JobsList.cshtml
@model List<BeMyNeighbor.Data.Entities.Post>
@{
  Layout = "../Shared/_UserMainLayout.cshtml";
}
  <div class="UserMainContent col-lg-11">
    <div class="PostHistory col-lg-5">
      <h4 class="ml-4">Post History</h4>
			@foreach (var item in Model){
				@if (@item.UserId != @item.UserSelectedId
				&& @item.UserId == BeMyNeighbor.Domain.Models.CurrentUser.Storage().UserDb.UserId){
						@Html.Partial("_PostedJobs",@item)
				}
			}
    </div>

		<div class="WorkList col-lg-6">
      <h4 class="ml-5">Your WorkList</h4>
			@foreach (var item in Model){
				@if (@item.UserId != BeMyNeighbor.Domain.Models.CurrentUser.Storage().UserDb.UserId){
						@Html.Partial("_AssignedJobs",@item)
				}
			}
    </div>
</div>

BeMyNeighbor.MVCClient/Views/Main/SelectCommunity.cshtml
@model BeMyNeighbor.Domain.Models.LocalUser;

@{
  Layout = "../Shared/_UserMainLayout.cshtml";
}

<div class="container">
    <main role="main" class="pb-1">
      @Html.Partial("./_SelectCommunity.cshtml", @Model)
    </main>
</div>

BeMyNeighbor.MVCClient/Views/Main/_AssignedJobs.cshtml
@model BeMyNeighbor.Data.Entities.Post
<div class="row justify-content-md-center">
  <div class="col-md-10 justify-content-md-center shadow p-3 mb-5 bg-white rounded">
    <ul id="Posts" class="list-group row m-1">
      <li class="list-group-item">
          <div class="PostContext d-flex">
            <img height='60'
                weight='60'
                class="timeline-image rounded-circle"
                src="https://static.intercomassets.com/avatars/1143992/square_128/Tiffany-1491608799.jpg?1491608799">
            <div class="PostText d-flex flex-column ml-3"> 
              <a href="">@Model.User.Username</a>
              <p>@Model.CommentTxt</p>
              @{
                <small>Task Description: @Model.TaskType.TaskDescription</small>
								<small>Reward Points: @Model.TaskType.TaskTypeRewardPoints</small>
								<small>Date Posted: @Model.DatePosted</small>
                <small>You Accepted Job on: @Model.DateSelected</small>
								<small>Job Done?: @Model.DoneFlag</small>
              } 
            </div>
          </div>
      </li>
    </ul>
  </div>
</div>

BeMyNeighbor.MVCClient/Views/Main/_PostedJobs.cshtml
@model BeMyNeighbor.Data.Entities.Post
<div class="row justify-content-md-center">
  <div class="col-md-10 justify-content-md-center shadow p-3 mb-5 bg-white rounded">
    <ul id="Posts" class="list-group row m-1">
      <li class="list-group-item">
        <form action = "/UserEvaluation/StartNewEvaluation" method = "post">
          <div class="PostContext d-flex">
            <img height='60'
                weight='60'
                class="timeline-image rounded-circle"
                src="https://static.intercomassets.com/avatars/1143992/square_128/Tiffany-1491608799.jpg?1491608799">
            <div class="PostText d-flex flex-column ml-3"> 
              <a href="">@Model.User.Username</a>
              <p>@Model.CommentTxt</p>
              @{
                <small>Task Description: @Model.TaskType.TaskDescription</small>
								<small>Date Posted: @Model.DatePosted</small>
                <small>Date Selected: @Model.DateSelected</small>
								<small>Job Done? @Model.DoneFlag</small>
              } 
            </div>
          </div>	
          @if(@Model.EvaluatedFlag==null){
              <input type=hidden name="postID" value =@Model.PostId>
              <input type=hidden name="selectedUserID" value =@Model.UserSelectedId>
              <input type=hidden name="taskTypeID" value =@Model.TaskTypeId>
              <button type='submit' class="btn btn-outline-primary float-right mt-2">Mark as done and evaluate now!</button>
          }	
          @Html.AntiForgeryToken()       			
        </form>
      </li>
    </ul>
  </div>
</div>

BeMyNeighbor.MVCClient/Views/Main/_SelectCommunity.cshtml
@model BeMyNeighbor.Domain.Models.LocalUser;

<div class="row justify-content-md-center">
  <div class="col-md-8">
    @{
      var stringGreeting = $"Welcome to BeMyNeighbor, {@Model.UserDb.Firstname} {@Model.UserDb.Lastname}!";
      <h4 class="text-center">@stringGreeting</h4>
    }
    <h6 class="text-center">Select a community in @Model.UserDb.Address.City</h6>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-md-5">

    <form class="d-flex flex-column justify-content-center ml-5" method="Post" action="/main/selectedcommunity">
      @if(@Model.Messages.MessageType == "UnableToFetchCommunities"){
        <div class="alert alert-danger text-center">@Model.Messages.MessageToUser</div>
      }
      @if(@Model.Messages.MessageType == "ErrorUpdatingCommunityOfUser"){
        <div class="alert alert-danger text-center">@Model.Messages.MessageToUser</div>        
      }
      <span class="text-center" style="color: red;" asp-validation-for="@Model.SelectedCommunity"></span>
      <fieldset name="CommunityRadioButtons" class="form-group" required>

        @foreach(var communityObject in @Model.CommunityList){
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <input type="radio" aria-label="Radio button for following text input" value="@communityObject.CommunityId" asp-for="@Model.SelectedCommunity">
              </div>
            </div>
            <label type="text" class="form-control">@communityObject.CommunityName</label>
          </div>
        }

      </fieldset>
      <button type="submit" class="btn btn-outline-primary float-right">Select</button>
    </form>
  </div>
</div>

BeMyNeighbor.MVCClient/Views/Shared/Post/_PostForm.cshtml
@model BeMyNeighbor.Domain.Models.ViewModels.CreatePostViewModel;
<div class="row justify-content-md-center">
  <div class="col-md-10 justify-content-md-center shadow p-3 mb-5 bg-white rounded">
    <p>New Job Post</p>
    <form action="/Post/Create" method="Post">
      <div class="form-group">
        <input class="form-control" maxlength="100" asp-for="@Model.UserComment">
      </div>
      <fieldset class="form-group">
        <select class="form-control" asp-for="@Model.TaskTypeId">
          @Html.Partial("_TaskTypeOptions.cshtml",BeMyNeighbor.Domain.Models.DbModels.TaskDbManager.GetInstance().TaskTypeList)
        </select>
      </fieldset>
      <button type="submit" class="btn btn-outline-primary float-right">Post Neighbor!</button>
    </form>
  </div>
</div> 

BeMyNeighbor.MVCClient/Views/Shared/Post/_PostItem.cshtml
@model Tuple<BeMyNeighbor.Data.Entities.User, BeMyNeighbor.Data.Entities.Post>
<div class="row justify-content-md-center">
  <div class="col-md-10 justify-content-md-center shadow p-3 mb-5 bg-white rounded">
    <ul id="Posts" class="list-group row m-1">
      <li class="list-group-item">
        <form action="/Main/SelectedJob" method="Post">
          <fieldset>
            <input value="@Model.Item2.PostId" style="visibility: hidden; margin-top:-30px;" name="selectedPostId"/>
            <div class="PostContext d-flex" style="margin-top: -18px;">
              <img height='60'
                  weight='60'
                  class="timeline-image rounded-circle"
                  src="https://static.intercomassets.com/avatars/1143992/square_128/Tiffany-1491608799.jpg?1491608799">
              <div class="PostText d-flex flex-column ml-3"> 
                <a href="">@Model.Item1.Username</a>
                <p>@Model.Item2.CommentTxt</p>
                @{
                  var taskText = BeMyNeighbor.Domain.Models.DbModels.PostDbManager.FindTask(@Model.Item2.TaskTypeId).TaskDescription;
                  <small>@taskText</small>
                } 
              </div>
            </div>
          </fieldset>

          @if((@Model.Item1.Username != BeMyNeighbor.Domain.Models.CurrentUser.Storage().UserDb.Username)
                && (Model.Item2.UserSelectedId != BeMyNeighbor.Domain.Models.CurrentUser.Storage().UserDb.UserId)){
            <button type='submit' class="btn btn-outline-primary float-right">Accept Job!</button>          
          }
          @if(@Model.Item2.UserSelectedId == BeMyNeighbor.Domain.Models.CurrentUser.Storage().UserDb.UserId){
              <small class="float-right">Selected by @Model.Item2.UserSelected.Username</small>
          }

        </form>
      </li>
    </ul>
  </div>
</div>

BeMyNeighbor.MVCClient/Views/Shared/Post/_TaskTypeOptions.cshtml
@model List<BeMyNeighbor.Data.Entities.Task>


@foreach (var item in Model)
{
		<option value=@item.TaskTypeId>@item.TaskDescription</option>
}

BeMyNeighbor.MVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeMyNeighbor.MVCClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/8b761430d4.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeMyNeighbor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <!-- <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> -->
                    </ul>
                    <ul class="navbar-nav mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark float-right" asp-controller="Auth" asp-action="SignIn">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark float-right" asp-controller="Auth" asp-action="SignUp">Sign Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BeMyNeighbor.MVCClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <partial name="../Shared/_ValidationScriptsPartial.cshtml" />
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

BeMyNeighbor.MVCClient/Views/Shared/_UserMainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeMyNeighbor.MVCClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <script src="https://kit.fontawesome.com/8b761430d4.js"></script>
  <link rel="stylesheet" href="@Url.Content("~/css/Main/index.css")" type="text/css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">BeMyNeighbor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                      <li class="nav-item">
                              <a class="nav-link text-dark" asp-controller="Main" asp-action="Index"><i class="fas fa-newspaper"></i> NeighborFeed</a>
                          </li>

                      <li class="nav-item">
                              <a class="nav-link text-dark" asp-controller="Main" asp-action="ViewJobList"><i class="far fa-list-alt"></i> JobList</a>
                          </li>
                      <li class="nav-item">
                              <a class="nav-link text-dark" asp-controller="UserEvaluation" asp-action="ViewEvaluationHistory"><i class="fas fa-clipboard"></i> EvalHistory</a>
                      </li>
                    </ul>
                    <ul class="navbar-nav mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark float-right"><i class="fas fa-cog"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark float-right" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BeMyNeighbor.MVCClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <partial name="../Shared/_ValidationScriptsPartial.cshtml" />
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>